# GoReleaser configuration for meow
# Documentation: https://goreleaser.com

version: 2

project_name: meow

before:
  hooks:
    - go mod tidy

builds:
  - id: meow
    main: ./cmd/meow
    binary: meow
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/meow-stack/meow-machine/cmd/meow/cmd.Version={{.Version}}

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "Merge pull request"
      - "Merge branch"

release:
  github:
    owner: akatz-ai
    name: meow-machine
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
